#!/bin/csh 

# MacPro cronjob:
# 35 04 * * * /opt/projects/cronjobs/go_gemc_doxygen



# make sure we have all versions
rm -rf   gemc_doxy
mkdir -p gemc_doxy
cd       gemc_doxy

git clone https://github.com/gemc/releases.git
cd releases

# for now, all versions
set versions = `ls`

echo
echo DOXYGEN for versions: $versions
echo

foreach v ($versions)
	echo
	echo Running $v
	cd $v
	cp /opt/projects/cronjobs/gemc_logo.gif .
	cp /opt/projects/gemc/docs/doxygen/Doxyfile .
	cp /opt/projects/gemc/docs/doxygen/doxygen.css .
	echo "PROJECT_NUMBER=$v" >> Doxyfile
	doxygen Doxyfile

	# moving it first, then copying, so I can omit
	# destination filename, otherwise may put it
	# in sub-dir (e.g. 2.0_beta1/2.0_beta1)
	mv html $v

	scp -r $v ftp:/u/group/clas/www/gemc/html/work/doxy

	cd ../
end

cd /opt/projects/cronjobs
scp table.css     ftp:/u/group/clas/www/gemc/html/work/doxy
scp gemc_logo.gif ftp:/u/group/clas/www/gemc/html/work/doxy
scp doxies.html   ftp:/u/group/clas/www/gemc/html/work/doxy

cd
rm -rf gemc_doxy
