#!/bin/csh 

set passwd = $2

if($1 == "help" || $1 == "doxy" || $1 == "databases" || $1 == "banks") then
	goto $1
endif


# GEMC help
help:
gemc -help-html
scp gemc_help.html ftp:/u/group/clas/www/gemc/html/gemc
rm gemc_help.html
if($1 == "help") exit


# GEMC Tables
databases:
rm -rf mysqlq ; mkdir mysqlq
cd mysqlq
set gemc_db = (cnd_devel ctof_devel dc12_devel ec_devel ft_devel htcc_devel micromegas_devel ftof_devel pcal_devel rich_devel svt_devel)

echo "<html>"                                           > main.html
echo "<br><br>"                                        >> main.html
echo " Active Databases: "                             >> main.html
echo "<br><br>"                                        >> main.html
foreach db ($gemc_db)
	echo "<a href=$db.html target=_blank> $db </a><br> " >> main.html
end
echo "<br><br>"                                        >> main.html
echo "</html>"                                         >> main.html

foreach db ($gemc_db)
	set par_tables = `mysql -h clasdb -u mauree -p$passwd $db -e "show tables"  | grep "__parameters"`
  set geo_tables = `mysql -h clasdb -u mauree -p$passwd $db -e "show tables"  | grep "__geometry"`
  set ele_table  = 'materials__elements'
	set mat_tables = `mysql -h clasdb -u mauree -p$passwd $db -e "show tables"  | grep "__materials"`
	set opt_tables = `mysql -h clasdb -u mauree -p$passwd $db -e "show tables"  | grep "__opt_properties"`
	echo "<html>"                                               > $db".html"
	echo "<br><br>"                                            >> $db".html"
	echo " Parameters tables in $db : "                        >> $db".html"
	echo "<br><br>"                                            >> $db".html"
	foreach pars ($par_tables)
		echo "<a href=$pars.html target=_blank> $pars </a><br> " >> $db".html"
	end
	echo "<br><br>"                                            >> $db".html"
	
	echo " Geometry tables in $db : "                          >> $db".html"
	echo "<br><br>"                                            >> $db".html"
	foreach geo ($geo_tables)
		echo "<a href=$geo.html target=_blank> $geo </a><br> "   >> $db".html"
	end
  echo "<br><br>"                                            >> $db".html"
  echo " Materials tables in $db : "                         >> $db".html"
  echo "<br><br>"                                            >> $db".html"
  foreach mats ($mat_tables)
    echo "<a href=$mats.html target=_blank> $mats </a><br> " >> $db".html"
  end
  
	echo "<br><br>"                                            >> $db".html"
	echo "</html>"                                             >> $db".html"
	
	# Parameters:
	foreach pars ($par_tables)
		echo "<html>"                                                                > $pars".html"
		echo "<br><br>"                                                             >> $pars".html"
		echo "<pre>"                                                                >> $pars".html"
		echo " $db  Parameters: "                                                   >> $pars".html"
		echo "<br><br>"                                                             >> $pars".html"
		mysql --html -h clasdb -u mauree -p$passwd $db -e "select * from $pars"     >> $pars".html"
		echo "</pre>"                                                               >> $pars".html"
		echo "<br><br>"                                                             >> $pars".html"
		echo "</html>"                                                              >> $pars".html"
	end	
	
	# Geometry:
	foreach geo ($geo_tables)
		echo "<html>"                                                                > $geo".html"
		echo "<br><br>"                                                             >> $geo".html"
		echo "<pre>"                                                                >> $geo".html"
		echo " $db  Parameters: "                                                   >> $geo".html"
		echo "<br><br>"                                                             >> $geo".html"
		mysql --html -h clasdb -u mauree -p$passwd $db -e "select * from $geo"      >> $geo".html"
		echo "</pre>"                                                               >> $geo".html"
		echo "<br><br>"                                                             >> $geo".html"
		echo "</html>"                                                              >> $geo".html"
	end
  
  # Materials:
  foreach mat ($mat_tables)
    echo "<html>"                                                                > $mat".html"
    echo "<br><br>"                                                             >> $mat".html"
    echo "<pre>"                                                                >> $mat".html"
    echo " $db  Materials: "                                                    >> $mat".html"
    echo "<br><br>"                                                             >> $mat".html"
    mysql --html -h clasdb -u mauree -p$passwd $db -e "select * from $mat"      >> $mat".html"
    echo "</pre>"                                                               >> $mat".html"
    echo "<br><br>"                                                             >> $mat".html"
    echo "</html>"                                                              >> $mat".html"
  end

	# Optical Properties:
	foreach opt ($opt_tables)
		echo "<html>"                                                                > $opt".html"
		echo "<br><br>"                                                             >> $opt".html"
		echo "<pre>"                                                                >> $opt".html"
		echo " $db  Optical Properties: "                                           >> $opt".html"
		echo "<br><br>"                                                             >> $opt".html"
		mysql --html -h clasdb -u mauree -p$passwd $db -e "select * from $opt"      >> $opt".html"
		echo "</pre>"                                                               >> $opt".html"
		echo "<br><br>"                                                             >> $opt".html"
		echo "</html>"                                                              >> $opt".html"
	end

 
  
end

# Elements:
echo "<html>"                                                                  > $ele_table".html"
echo "<br><br>"                                                               >> $ele_table".html"
echo "<pre>"                                                                  >> $ele_table".html"
echo " Elements in clas12_geometry:"                                          >> $ele_table".html"
echo "<br><br>"                                                               >> $ele_table".html"
mysql --html -h clasdb -u mauree -p$passwd clas12_geometry -e "select * from $ele_table"  >> $ele_table".html"
echo "</pre>"                                                                 >> $ele_table".html"
echo "<br><br>"                                                               >> $ele_table".html"
echo "</html>"                                                                >> $ele_table".html"




cd ..
scp -r mysqlq ftp:/u/group/clas/www/gemc/html/work
rm -rf mysqlq
if($1 == "databases") exit




# GEMC banks
banks:
rm -rf mysqlq_banks ; mkdir mysqlq_banks
cd mysqlq_banks
set gemc_banks = (`mysql -h clasdb -u clasuser clas12_banks -e "show tables" | grep -v Tables_in_clas12_banks`)
foreach b ($gemc_banks)
	echo "<html>"                                                                > $b".html"
	echo "<br><br>"                                                             >> $b".html"
	echo "<pre>"                                                                >> $b".html"
	echo " Bank $b : "                                                          >> $b".html"
	echo "<br><br>"                                                             >> $b".html"
	echo " Type : 0 = integer , 1 = double "                                    >> $b".html"
	echo "<br>"                                                                 >> $b".html"
	echo " Activated : 0 = not in the output , 1 = in the output "              >> $b".html"
	echo "<br><br>"                                                             >> $b".html"
	mysql --html -h clasdb -u clasuser clas12_banks -e "select * from $b"       >> $b".html"
	echo "</pre>"                                                               >> $b".html"
	echo "<br><br>"                                                             >> $b".html"
	echo "</html>"                                                              >> $b".html"
end
cd ..
scp -r mysqlq_banks ftp:/u/group/clas/www/gemc/html/work
rm -rf mysqlq_banks
if($1 == "banks") exit














